version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: urlshortener_db
    ports:
      - "5436:5432"

  application:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database